### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Cylix** [dimagi/datadog-checks#18]
Hey all,

Thanks for the base scripts, very useful!

I'd like to use your base script for celery monitoring and tune it for our use case at Whova to start monitoring our celery queues.

Do you have any specific license regarding this, or is that free of use/modifications?

Thanks!

**Comment by czue** [comment]
Hi @Cylix - thanks for the note. We've added a permissive license in https://github.com/dimagi/datadog-checks/pull/19

Glad you found this project helpful! If you do make any changes you think would benefit the broader community please don't hesitate to send them back here.
